layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Test-time Adaptation
    web_url: https://github.com/search?q=Test-time%20adaptation&type=repositories
    image_url: https://raw.githubusercontent.com/tim-learn/awesome-test-time-adaptation/refs/heads/main/TTA.png

  - name: 3D Point Cloud
    web_url: https://github.com/search?q=3D+Point+Cloud&type=repositories
    image_url: https://apollo-studio-public.bj.bcebos.com/community/article/image/b40e1efb6bfd2d108f33bf67af29e521c7fcff29

  - name: 3D Semantic Segmentation
    web_url: https://github.com/search?q=3D+Semantic+Segmentation&type=repositories
    image_url: https://camo.githubusercontent.com/b744bc4ad2b502a5fe0c3034b75445fe22e71779868941e3be91d6401eec132e/68747470733a2f2f6e76696469612e6769746875622e696f2f4d696e6b6f77736b69456e67696e652f5f696d616765732f7365676d656e746174696f6e2e706e67
